name: dukkha installer
description: Install dukkha
author: The Arhat Dev Authors
branding:
  color: blue
inputs:
  image:
    description: image containing /dukkha
    default: ghcr.io/arhat-dev/dukkha:latest
runs:
  using: composite
  steps:
  - shell: bash
    run: |
      bash "${GITHUB_ACTION_PATH}/install-dukkha.sh" "${{ inputs.image }}"
