name: dukkha installer
description: Install dukkha
author: The Arhat Dev Authors
branding:
  color: blue
inputs:
  version:
    description: dukkha version
    default: latest
  go-version:
    description: golang version to compile sget from source
    default: 1.17.x

runs:
  using: composite
  steps:
  - uses: actions/setup-go@v2
    with:
      go-version: ${{ inputs.go-version }}

  - shell: bash
    run: |
      bash "${GITHUB_ACTION_PATH}/install-dukkha.sh" "${{ inputs.version }}"
