name: dukkha installer
description: Install dukkha
author: The Arhat Dev Authors
branding:
  color: blue
inputs:
  version:
    description: dukkha version
    default: latest

runs:
  using: composite
  steps:
  # setup go to build sget
  - uses: actions/setup-go@v2
    with:
      go-version: 1.16.x

  - shell: bash
    run: |
      bash "${GITHUB_ACTION_PATH}/install-dukkha.sh" "${{ inputs.version }}"
