name: CI

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      reason:
        description: reason to run this workflow
        required: false
        default: test
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: |
        make lint.all

    - name: Install dukkha
      uses: arhat-dev/actions-setup-dukkha@master

    - name: Check dukkha installed
      run: |-
        if ! command -v dukkha ; then
          echo "dukkha NOT INSTALLED to PATH!"
          exit 1
        fi

        dukkha version
