name: CI

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      reason:
        description: reason to run this workflow
        required: false
        default: test
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  check:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      if: ${{ matrix.os }} == "ubuntu-latest"
      run: |
        make lint.all

    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Install dukkha
      uses: arhat-dev/actions-setup-dukkha@master

    - name: Check dukkha installed
      run: |-
        if ! command -v dukkha ; then
          echo "dukkha NOT INSTALLED to PATH!"
          exit 1
        fi

        dukkha version
